# Generated by Django 4.2.20 on 2025-04-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='code',
            field=models.CharField(default=0, max_length=6, unique=True),
        ),
    ]
