# Generated by Django 4.2.20 on 2025-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_passwordresettoken_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conteudo',
            name='tema',
            field=models.CharField(choices=[('Matemática', 'Matemática'), ('Português', 'Português'), ('História', 'História'), ('Geografia', 'Geografia'), ('Inglês', 'Inglês')], max_length=100),
        ),
    ]
