# Generated by Django 4.2.20 on 2025-05-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conteudo_is_active_alter_conteudo_tema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Progresso',
        ),
    ]
