# Generated by Django 4.2.20 on 2025-06-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='serie_atual',
            field=models.CharField(blank=True, choices=[('1º Ano', '1º Ano'), ('2º Ano', '2º Ano'), ('3º Ano', '3º Ano')], max_length=10, null=True),
        ),
    ]
