# Generated by Django 4.2.20 on 2025-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_perfilusuario_serie_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
