# Generated by Django 4.2.20 on 2025-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_perfilusuario_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/provas/'),
        ),
    ]
